export default [
{roomId: `If you already had sex with someone and found out y’all where related, would you have sex with them again?`}, 
{roomId: `What’s something you learned in high school that you currently use in adulthood?`}, 
{roomId: `Did your football team make it to the Super Bowl?`}, 
{roomId: `How many ppl do you think have seen you have sex?`}, 
{roomId: `Have you ever had to save someone’s life? If so, what happened?`}, 
{roomId: `Ladies: How do you give or show consent to let someone know you are ok with them touching you?`}, 
{roomId: `Do you have anybody it’s currently “on sight” for?`}, 
{roomId: `FITB: I like my partner to smell like____. `}, 
{roomId: `Are you sensitive?`}, 
{roomId: `On a scale of 1-10, 10 being the highest, how important is your friends opinion of who you are dating?`},  
{roomId: `Who’s the person you find it the hardest to set boundaries with?`}, 
{roomId: `How long does it take you to go from home to work?`}, 
{roomId: `Have you ever dated someone you were genuinely not attracted to?`}, 
{roomId: `Would you prefer a job the physically taxing or mentally taxing?`}, 
{roomId: `Fellas, what size pants do you wear?`}, 
{roomId: `What store do you shop in most often?`}, 
{roomId: `Do you want to get married?`},
{roomId: `What percent is your phone battery on?`}, 
{roomId: `What’s the funniest thing you’ve ever did?`}, 
{roomId: `How do you reenergize?`}, 
{roomId: `Ladies, would you participate in “struggle love” if knew it was true love?`}, 
{roomId: `What’s the first thing you take off when feel yourself getting hot?`}, 
{roomId: `Have you ever snored your self awake?`}, 
{roomId: ` Would you date a porn star?`}, 
{roomId: `Do you brush your teeth after waking up from a nap?`}, 
{roomId: `How do you like your eggs?`}, 
{roomId: `To my black LGBTQIA+ family, what do you find more offensive, being called a homophobic slur (fag,faggot,dyke) or a racial slur (nigger,coon,”boy”)?`}, 
{roomId: `What’s your grandmother’s, on your mother’s side, oldest child’s name?`}, 
{roomId: `Have you ever shit in the shower?`}, 
{roomId: `Who played Joker better, Jack Nickelson or Heath Legder?`}, 
{roomId: `How has Donald Trump being president effected your life personally?`}, 
{roomId: `Outside of your signature when was the time you've used cursive?`}, 
{roomId: `How many years have you been sexually active?`}, 
{roomId: `What are your sexual requirements?`}, 
{roomId: `Is your parents relationship your relationship goals?`}, 
{roomId: `What kind of porn do you like to watch?`}, 
{roomId: `On a scale of 1-10, (1 low 10 high) how much do you like your body?`}, 
{roomId: `What's the first thing you do after you get out of the shower?`}, 
{roomId: `How long have you been at your current job?`}, 
{roomId: `How do you reward yourself?`}, 
{roomId: `What are the side effects of being in a relationship with you?`}, 
{roomId: `What television show would you like to see a reboot of?`}, 
{roomId: `What's the last thing you talked to God about?`}, 
{roomId: `Are you friends with your siblings?`},
{roomId: `Did you use a condom the last time you had sex?`}, 
{roomId: `Is being “ghetto” a bad thing?`},
{roomId: `Sweet snacks or Salty snacks?`}, 
{roomId: `How long does it take you to fall asleep?`},
{roomId: `Ladies: Have you ever taken your bra off at work?`}, 
{roomId: `What’s the “freakiest” thing you ever done at work?`}, 
{roomId: `What city is the “messiest” person you know from?`},  
{roomId: `What’s the you’ve ever been on vacation?`}, 
{roomId: `What’s you favorite smell?`}, 
{roomId: `Fellas: The last time you asked a women for her number what made you ask?`},
{roomId: `How long does it take you to go from home to work?`}, 
{roomId: `Have you ever dated someone you were genuinely not attracted to?`}, 
{roomId: `Would you prefer a job the physically taxing or mentally taxing?`}, 
{roomId: `Fellas, what size pants do you wear?`}, 
{roomId: `What store do you shop in most often?`}, 
{roomId: `Do you want to get married?`},
{roomId: `What percent is your phone battery on?`}, 
{roomId: `What’s the funniest thing you’ve ever did?`}, 
{roomId: `How do you reenergize?`}, 
{roomId: `Ladies, would you participate in “struggle love” if knew it was true love?`}, 
{roomId: `What’s the first thing you take off when feel yourself getting hot?`}, 
{roomId: `Have you ever snored your self awake?`}, 
{roomId: `Would you date a porn star?`}, 
{roomId: `Do you brush your teeth after waking up from a nap?`}, 
{roomId: `How do you like your eggs?`}, 
{roomId: `To my black LGBTQIA+ family, what do you find more offensive, being called a homophobic slur (fag,faggot,dyke) or a racial slur (nigger,coon,”boy”)?`}, 
{roomId: `What’s your grandmother’s, on your mother’s side, oldest child’s name?`}, 
{roomId: `Have you ever shit in the shower?`}, 
{roomId: `Who played Joker better, Jack Nickelson or Heath Legder?`}, 
{roomId: `How has Donald Trump being president effected your life personally?`}, 
{roomId: `Outside of your signature when was the time you've used cursive?`}, 
{roomId: `How many years have you been sexually active?`}, 
{roomId: `What are your sexual requirements?`}, 
{roomId: `Is your parents relationship your relationship goals?`}, 
{roomId: `What kind of porn do you like to watch?`}, 
{roomId: `On a scale of 1-10, (1 low 10 high) how much do you like your body?`}, 
{roomId: `What's the first thing you do after you get out of the shower?`}, 
{roomId: `How long have you been at your current job?`}, 
{roomId: `How do you reward yourself?`}, 
{roomId: `What are the side effects of being in a relationship with you?`}, 
{roomId: `What television show would you like to see a reboot of?`}, 
{roomId: `What's the last thing you talked to God about?`}, 
{roomId: `Are you friends with your siblings?`},
{roomId: `Did you use a condom the last time you had sex?`}, 
{roomId: `Is being “ghetto” a bad thing?`},
{roomId: `Sweet snacks or Salty snacks?`}, 
{roomId: `How long does it take you to fall asleep?`},
{roomId: `Ladies: Have you ever taken your bra off at work?`}, 
{roomId: `What’s the “freakiest” thing you ever done at work?`}, 
{roomId: `What city is the “messiest” person you know from?`},  
{roomId: `What’s the you’ve ever been on vacation?`}, 
{roomId: `What’s you favorite smell?`}, 
{roomId: `Fellas: The last time you asked a women for her number what made you ask?`},
{roomId: `Ladies, when was the last time you took some type of emergency contraceptive?, (plan b)`},
{roomId: `Fellas how many plan b’s have you paid for or went half on?`}, 
{roomId: `What game are you really good at?`}, 
{roomId: `What’s your biggest insecurity?`}, 
{roomId: `Fellas, who’s the last person that twerked on you?`}, 
{roomId: `What’s your favorite Oscar winning movies?`}, 
{roomId: `How many phone numbers do you know by heart?`}, 
{roomId: `What do you listen to when getting ready for work in the morning?`}, 
{roomId: `Are you ok with your current relationship status?, Why or why not?`}, 
{roomId: `How do you order your steak?`}, 
{roomId: `In your opinion how many sexual partners are to many?`}, 
{roomId: `Have you ever caught one of your parents (not necessarily together) ￼having sex?`}, 
{roomId: `How’s life treating you?`}, 
{roomId: `On a scale of 1-10, 10 being the highest, how seriously do you take a pinky promise?`}, 
{roomId: `What’s the name of the street you grow up on?`}, 
{roomId: `On a scale of 1-10, 10 being very open, how sexually fluid are you?`}, 
{roomId: `What was your go to video game growing up?`},
{roomId: `Can I see (take a pic) what’s in your “junk drawer”?`}, 
{roomId: `Is love enough?`}, 
{roomId: `Would you rather be first or last?`}, 
{roomId: `What’s the last sacrifice you made?`}, 
{roomId: `What would you say you learned from your last relationship?`},
{roomId: `Fellas, are you open to sexual criticism?`}, 
{roomId: `Is being “ghetto” a bad thing?`},
{roomId: `Sweet snacks or Salty snacks?`}, 
{roomId: `How long does it take you to fall asleep?`},
{roomId: `Ladies: Have you ever taken your bra off at work?`}, 
{roomId: `What’s the “freakiest” thing you ever done at work?`}, 
{roomId: `What city is the “messiest” person you know from?`},  
{roomId: `What’s the you’ve ever been on vacation?`}, 
{roomId: `What’s you favorite smell?`}, 
{roomId: `Fellas: The last time you asked a women for her number what made you ask?`},
{roomId: `Fellas, what size pants do you wear?`}, 
{roomId: `What store do you shop in most often?`}, 
{roomId: `Do you want to get married?`},
{roomId: `What percent is your phone battery on?`}, 
{roomId: `What’s the funniest thing you’ve ever did?`}, 
{roomId: `How do you reenergize?`}, 
{roomId: `Ladies, would you participate in “struggle love” if knew it was true love?`}, 
{roomId: `Would you date (insert your name)?`}, 
{roomId: `What are you leaving in 2018?`}, 
{roomId: `What are you taking to 2019?`}
]